version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo "Waiting"
      - aws ec2 stop-instances --instance-ids i-0485f67b594476a29
      - aws ec2 start-instances --instance-ids i-092d4220195d173f6
      - aws ec2 wait instance-status-ok --instance-ids i-092d4220195d173f6
      - npm install yarn -g
      - yarn install
  build:
    commands:
      - yarn android.app
  post_build:
    commands:
      - yarn report:generate
      - aws ec2 stop-instances --instance-ids i-092d4220195d173f6
      - aws s3 rm s3://bienestar-conmigo-app-test-automation-reports/ --recursive
      - aws s3 sync test-report s3://bienestar-conmigo-app-test-automation-reports/
      - aws ec2 start-instances --instance-ids i-0485f67b594476a29

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: test-report